import os
from langchain_community.document_loaders import PyPDFLoader,PyMuPDFLoader 
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pathlib import Path ## for handling file paths
import numpy as np
from sentence_transformers import SentenceTransformer ## used for generating embeddings
import chromadb ## ChromaDB for vector database
from chromadb.config import Settings ## uses for ChromaDB settings
import uuid ## for generating unique IDs
from typing import List,Dict,Any,Tuple ## for type hinting

import chromadb
from langchain_community.vectorstores import Chroma

## read all files from directory and load into a list of documents

def load_pdfs_from_directory(directory_path):
    all_documents = []
    pdf_directory= Path(directory_path)
    pdf_files=list(pdf_directory.glob("**/*.pdf")) ## get all pdf files in the directory
    print(f"Found {len(pdf_files)} PDF files in the directory.")
    for pdf_file in pdf_files:
        print(f"Loading PDF: {pdf_file.name}")
        try:
            loader = PyPDFLoader(str(pdf_file))
            documents = loader.load()
            for doc in documents:
                doc.metadata["source"] = pdf_file.name  ## add source metadata to each document
                doc.metadata["file_path"] = str(pdf_file)  ## add file path metadata to each document
            all_documents.extend(documents)## add documents from this PDF to the overall list
            print(f"Loaded {len(documents)} pages from {pdf_file.name}")
        except Exception as e:
            print(f"Error loading {pdf_file.name}: {e}")
    print(f"Total documents loaded: {len(all_documents)}")
    return all_documents


### text splitiing get in to smaller chunks
def split_documents(documents,chunk_size=1000,chunk_overlap=200):## chunk_overlap is the number of characters that will overlap between chunks
    """Split documents into smaller chunks."""
    text_splitter=RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,## number of characters that will overlap between chunks
        length_function=len,
        separators=["\n\n", "\n", " ", ""]## list of separators to use for splitting
    )
    split_docs=text_splitter.split_documents(documents)
    print(f"Split {len(documents)} documents in to {len(split_docs)} chunks")

    #show example chunks
    if split_docs:
        print(f"\nExample chunk:")
        print(f"content:{split_docs[0].page_content[:200]}...")## print first 200 characters of the first chunk
        print(f"metadata:{split_docs[0].metadata}")## print metadata of the first chunk
    return split_docs

class EmbeddingManager:
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        """Initialize the embedding manager with a specified model.
        Args:
            model_name (str): The name of the sentence transformer model to use for generating embeddings.
        """
        self.model_name = model_name ## store the model name for later use
        self.model = None ## initialize the model attribute to None
        self._load_model() ## invoke the method to load the model 

    def _load_model(self):
        """Load the sentence transformer model."""
        try:
            print(f"Loading model: {self.model_name}...")
            self.model = SentenceTransformer(self.model_name) ## load the specified sentence transformer model
            print("Model loaded successfully.embeding dimension:", self.model.get_sentence_embedding_dimension()) ## print the dimension of the embeddings generated by the model
        except Exception as e:
            print(f"Error loading model: {e}")
            raise e

    def generate_embeddings(self, texts: List[str]) -> np.ndarray:
        """Generate embeddings for a list of texts.
        Args:
            texts (List[str]): A list of strings for which to generate embeddings.
        Returns:
            np.ndarray: An array of embeddings corresponding to the input texts.
        """
        if not self.model:
            raise ValueError("Model not loaded. Cannot generate embeddings.")
        print(f"Generating embeddings for {len(texts)} texts...")
        embeddings=self.model.encode(texts, show_progress_bar=True) ## generate embeddings for the input texts
        print("Embeddings generated successfully with shape:", embeddings.shape) ## print the shape of the generated embeddings
        return embeddings
    
## store the generated embeddings in ChromaDB vector database
class VectorStoreManager:
    def __init__(self, collection_name: str = "pdf_embeddings", persist_directory: str = "../data/vectorStore"):
        """Initialize the vector store manager with ChromaDB settings.
        Args:
            collection_name (str): The name of the collection to store embeddings in ChromaDB.
            persist_directory (str): The directory where ChromaDB will persist its data.
        """
        self.collection_name = collection_name ## store the collection name for later use
        self.persist_directory = persist_directory ## store the persist directory for later use
        self.client = None ## initialize the ChromaDB client attribute to None
        self.collection = None ## initialize the collection attribute to None
        self._initialize_store() ## invoke the method to initialize ChromaDB

    def _initialize_store(self):
        """Initialize the ChromaDB client and collection."""
        try:
            ##create persisst directory if it does not exist
            os.makedirs(self.persist_directory, exist_ok=True)
            self.client=chromadb.PersistentClient(path=self.persist_directory) ## initialize the ChromaDB client with the specified persist directory

            ##create or get the collection for storing embeddings
            self.collection=self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={"description": "pdf document embeddings for rag application"}
                )
            print(f"ChromaDB collection '{self.collection_name}' initialized successfully.")
            print(f"existing documents in collection: {self.collection.count()}") ## print the number of existing documents in the collection
        except Exception as e:
            print(f"Error initializing ChromaDB: {e}")
            raise e
    def add_documents(self, documents: List[Any], embeddings: np.ndarray):
        """Add documents and their corresponding embeddings to the ChromaDB collection.
        Args:
            documents (List[Dict[str, Any]]): A list of dictionaries containing document metadata and content.
            embeddings (np.ndarray): An array of embeddings corresponding to the input documents.
        """
        if len(documents)!=len(embeddings):
            raise ValueError("number of documents and embeddings must be the same")
        print(f"adding {len(documents)} documents to the vector store...")

        ##prepare data for chromadb
        ids=[]
        metadatas=[]
        documents_text=[]
        embedding_list=[]

        for i, (doc, embedding) in enumerate(zip(documents, embeddings)):
            doc_id=f"doc_{uuid.uuid4().hex[:8]}_{i}" ## generate a unique ID for each document
            ids.append(doc_id)
            ## prepare metadata
            metadata=dict(doc.metadata)
            metadata["doc_index"]=i
            metadata["content_length"]=len(doc.page_content)
            metadatas.append(metadata)

            ##docuent content

            documents_text.append(doc.page_content)

            ## embedding
            embedding_list.append(embedding.tolist())

        ##add to chromadb collection
        try:
            self.collection.add(
                ids=ids,
                embeddings=embedding_list,
                metadatas=metadatas,
                documents=documents_text
            )
            print(f"successfully added {len(documents)} documents to the vector store. total documents in the collection:{self.collection.count()}")
        except Exception as e:
            print(f"error adding documents to the vector store:{e}")
            raise


